import type { Express, Request, Response } from "express";
import express from "express";
import { z } from "zod";
import { getStorage } from "./storage.js";
import { isDbConfigured, pingDb } from "./db.js";
import { isObsConfigured, pingObs, getObsBucket, getObsEndpoint } from "./obs.js";
import {
  getObjectStore,
  generateStorageKey,
  isAllowedNamespace,
  ALLOWED_NAMESPACES,
  MAX_UPLOAD_BYTES,
  type ObjectNamespace,
} from "./object-store.js";
import { renderReportPdf, renderReportXml } from "./report-render.js";
import {
  insertCustomerSchema, insertCustomerDocumentSchema, insertCustomerActionSchema,
  insertRuleSchema, insertRuleSimulationSchema, insertAlertSchema, insertCaseSchema,
  insertRegulatoryReportSchema, insertFraudRegisterSchema, insertTransactionSchema,
  insertUserSchema, insertRoleSchema, insertUserRoleAssignmentSchema,
  type ModelRow, type ModelEvaluationRow, type InsertModel, type InsertModelEvaluation,
} from "../shared/schema.js";
import type { TransactionFilters } from "./storage.js";
import {
  requireActor as authRequireActor,
  getActorUserId,
  setSessionCookie,
  clearSessionCookie,
  verifyPassword,
  hashPassword,
} from "./auth.js";

function requireDb(_req: Request, res: Response, next: () => void) {
  if (!isDbConfigured()) {
    return res.status(503).json({ error: "Database not configured. Set HUAWEI_PG* env vars." });
  }
  next();
}

const CreateCustomerBody = z.object({
  customer: insertCustomerSchema,
  documents: z.array(insertCustomerDocumentSchema.omit({ customerId: true })).optional().default([]),
});

const AppendActionBody = insertCustomerActionSchema;

const CreateUserBody = insertUserSchema.extend({
  email: z.string().email(),
  name: z.string().min(1),
});
const UpdateUserBody = insertUserSchema.partial();

// NOTE: insertRoleSchema is generated by drizzle-zod (Zod v4 internals)
// while this file's `z` is Zod v3, so we cannot safely `.extend()` or
// `.partial()` it without tripping cross-version "expected a Zod schema"
// errors during parse. The underlying `roles` table already constrains
// `name` NOT NULL and the other fields have safe defaults, so we use
// the generated schema directly for create, and a hand-rolled v3 schema
// for the partial PATCH body (so .extend/.partial isn't needed).
const CreateRoleBody = insertRoleSchema;
const UpdateRoleBody = z.object({
  name: z.string().min(1).optional(),
  label: z.string().optional(),
  description: z.string().optional(),
  privilegeLevel: z.string().optional(),
  permissionKeys: z.array(z.string()).optional(),
});

const AssignRoleBody = insertUserRoleAssignmentSchema;

function asyncHandler(fn: (req: Request, res: Response) => Promise<unknown>) {
  return (req: Request, res: Response) => {
    fn(req, res).catch((e) => {
      const msg = e instanceof Error ? e.message : String(e);
      const cause = (e as { cause?: unknown })?.cause;
      const causeMsg = cause instanceof Error ? cause.message : (cause ? String(cause) : "");
      console.error("[api]", req.method, req.path, "->", msg, causeMsg ? `\n  cause: ${causeMsg}` : "");
      if (!res.headersSent) {
        // Only echo the underlying DB cause to clients in non-production so
        // production deployments don't leak schema/SQL details.
        const body: { error: string; cause?: string } = { error: msg };
        if (causeMsg && process.env.NODE_ENV !== "production") body.cause = causeMsg;
        res.status(500).json(body);
      }
    });
  };
}

// Authn gate: resolves the acting user from the verified session cookie
// (Task #48). In non-production builds we additionally accept the legacy
// `x-actor-user-id` header so the dev "Act as (demo)" switcher keeps
// working without going through the login flow.
const requireActor = authRequireActor;

/**
 * Resolve the union of permissionKeys for the actor's roles. Used by
 * `requirePermission()` middleware and the `/api/users/me/permissions`
 * endpoint that the client `usePermissions()` hook calls. Admin role is
 * treated as a superuser (gets every permission).
 */
async function resolveActorPermissions(actorId: string): Promise<{ user: { id: string; name: string; roles: string[] } | null; permissions: Set<string> }> {
  const user = await getStorage().getUser(actorId);
  if (!user) return { user: null, permissions: new Set() };
  const allRoles = await getStorage().listRoles();
  // Authoritative: derive roles from user_role_assignments so the assignment
  // mutations (assignRole/unassignRole) drive effective permissions and
  // cannot drift from the cached user.roles[] mirror.
  const assignments = await getStorage().listAssignments();
  const assignedRoleIds = new Set(assignments.filter(a => a.userId === actorId).map(a => a.roleId));
  const assignedRoleNames = allRoles.filter(r => assignedRoleIds.has(r.id)).map(r => r.name);
  // Fallback to the embedded user.roles[] / user.role mirror for legacy rows
  // that have no assignments yet (so the system stays usable pre-reconcile).
  const fallbackRoles = (user.roles as string[] | null)?.length ? (user.roles as string[]) : (user.role ? [user.role] : []);
  const userRoles = assignedRoleNames.length ? assignedRoleNames : fallbackRoles;
  const matched = allRoles.filter((r) => userRoles.includes(r.name));
  const isAdmin = userRoles.includes("admin");
  const perms = new Set<string>();
  for (const r of matched) for (const p of (r.permissionKeys ?? [])) perms.add(p);
  if (isAdmin) {
    // Admin is a superuser even if the row's permissionKeys drift.
    for (const r of allRoles) for (const p of (r.permissionKeys ?? [])) perms.add(p);
  }
  return { user: { id: user.id, name: user.name, roles: userRoles }, permissions: perms };
}

/**
 * Express middleware factory: gates a route on a specific permission key.
 * Resolves the acting user from `x-actor-user-id`, expands their roles
 * to the union of permissionKeys, and rejects with 403 when missing.
 *
 * Defence-in-depth: the client `usePermissions()` hook also hides or
 * disables matching buttons, but the server is the source of truth.
 */
function requirePermission(key: string) {
  return async (req: Request, res: Response, next: () => void) => {
    try {
      const id = getActorUserId(req);
      if (!id) return res.status(401).json({ error: "Not signed in." });
      const { user, permissions } = await resolveActorPermissions(id);
      if (!user) return res.status(403).json({ error: "Unknown actor — user not registered." });
      if (!permissions.has(key)) return res.status(403).json({ error: `Your role does not allow this action (requires '${key}').` });
      next();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[requirePermission]", req.method, req.path, "->", msg);
      res.status(500).json({ error: "Permission check failed." });
    }
  };
}

// Build an actor descriptor for audit-log entries. Source of truth is the
// verified session-derived actor id (set by requireActor); the user's stored
// display name is also stashed on the request by requireActor so audit
// entries always reflect the verified user, not whatever the client sends.
// Strip credential material before returning user rows over the API. The
// `users` table now carries `passwordHash` (Task #48); it must never appear
// in any HTTP response. Apply to every list/detail/create/update payload.
function sanitizeUser<T extends Record<string, unknown>>(u: T): Omit<T, "passwordHash" | "passwordUpdatedAt"> {
  const { passwordHash: _ph, passwordUpdatedAt: _pu, ...rest } = u as T & { passwordHash?: unknown; passwordUpdatedAt?: unknown };
  return rest;
}

function actorFromReq(req: Request): { actorUserId?: string; actorName: string; ipAddress?: string } {
  const id = getActorUserId(req);
  const ip = req.ip || req.socket.remoteAddress || undefined;
  // Actor name is sourced exclusively from the verified session user record
  // (stamped on req by requireActor). Never trust client-supplied headers
  // or body fields for audit attribution.
  return {
    actorUserId: id ?? undefined,
    actorName: (req as Request & { actorName?: string }).actorName || "system",
    ipAddress: ip,
  };
}

export function registerDataRoutes(app: Express) {
  // ---------- Dashboard aggregates ----------
  app.get("/api/dashboard/kpis", requireDb, asyncHandler(async (_req, res) => {
    res.json(await getStorage().getDashboardKpis());
  }));

  app.get("/api/dashboard/trends", requireDb, asyncHandler(async (req, res) => {
    const w = (typeof req.query.window === "string" ? req.query.window : "7d") as "24h" | "7d" | "30d";
    const window: "24h" | "7d" | "30d" = w === "24h" || w === "30d" ? w : "7d";
    res.json(await getStorage().getDashboardTrends(window));
  }));

  app.get("/api/dashboard/compliance-snapshot", requireDb, asyncHandler(async (_req, res) => {
    res.json(await getStorage().getComplianceSnapshot());
  }));

  // ---------- Analytics aggregates (per-tab) ----------
  const ANALYTICS_TAB_SET = new Set([
    "executive","fraud","aml","models","rules","geography","channels","users","operations","audit",
  ] as const);
  const ANALYTICS_RANGES = new Set(["24h","7d","30d","90d"] as const);
  const ANALYTICS_CHANNELS = new Set(["all","pos","web","mobile","atm","branch"] as const);
  app.get("/api/analytics/:tab", requireDb, asyncHandler(async (req, res) => {
    const tab = req.params.tab as
      "executive"|"fraud"|"aml"|"models"|"rules"|"geography"|"channels"|"users"|"operations"|"audit";
    if (!ANALYTICS_TAB_SET.has(tab)) {
      return res.status(400).json({ error: `Unknown analytics tab: ${req.params.tab}` });
    }
    const rangeQ = (typeof req.query.timeRange === "string" ? req.query.timeRange : "30d") as
      "24h"|"7d"|"30d"|"90d";
    const channelQ = (typeof req.query.channel === "string" ? req.query.channel : "all") as
      "all"|"pos"|"web"|"mobile"|"atm"|"branch";
    const country = (typeof req.query.country === "string" && req.query.country.trim())
      ? req.query.country.trim() : "all";
    const filters = {
      timeRange: ANALYTICS_RANGES.has(rangeQ) ? rangeQ : "30d",
      channel: ANALYTICS_CHANNELS.has(channelQ) ? channelQ : "all",
      country,
    } as const;
    res.json(await getStorage().getAnalytics(tab, filters));
  }));

  // ---------- Graph Network workspace ----------
  app.get("/api/graph/network", requireDb, asyncHandler(async (req, res) => {
    const wRaw = typeof req.query.window === "string" ? req.query.window : "all";
    const window: "24h" | "7d" | "30d" | "all" =
      wRaw === "24h" || wRaw === "7d" || wRaw === "30d" ? wRaw : "all";
    const riskLevel = typeof req.query.riskLevel === "string" ? req.query.riskLevel : undefined;
    const entityType = typeof req.query.entityType === "string" ? req.query.entityType : undefined;
    const edgeType = typeof req.query.edgeType === "string" ? req.query.edgeType : undefined;
    const limit = req.query.limit
      ? Math.min(Math.max(parseInt(String(req.query.limit), 10) || 60, 5), 200)
      : undefined;
    res.json(await getStorage().getGraphNetwork({ window, riskLevel, entityType, edgeType, limit }));
  }));

  app.get("/api/system/db-health", asyncHandler(async (_req, res) => {
    if (!isDbConfigured()) return res.status(503).json({ ok: false, error: "DB not configured" });
    const r = await pingDb();
    res.status(r.ok ? 200 : 503).json(r);
  }));

  app.get("/api/system/obs-health", asyncHandler(async (_req, res) => {
    // Unconfigured branch reads env directly so a misconfigured production
    // (where getObjectStore() throws) still returns a structured 503 instead
    // of a generic 500.
    if (!isObsConfigured()) {
      return res.status(503).json({
        ok: false,
        configured: false,
        bucket: process.env.HUAWEI_OBS_BUCKET || "",
        endpoint: process.env.HUAWEI_OBS_ENDPOINT || "",
        backend: process.env.NODE_ENV === "production" ? "unavailable" : "memory",
        error:
          process.env.NODE_ENV === "production"
            ? "OBS not configured. Production refuses in-memory fallback — set HUAWEI_OBS_AK / HUAWEI_OBS_SK / HUAWEI_OBS_ENDPOINT / HUAWEI_OBS_BUCKET."
            : "OBS not configured. Using in-memory fallback (DEV ONLY) — set HUAWEI_OBS_* secrets to use real storage.",
      });
    }
    try {
      const r = await pingObs();
      res.status(r.ok ? 200 : 503).json({ configured: true, ...r });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[obs-health] init failed:", msg);
      res.status(503).json({
        ok: false,
        configured: true,
        bucket: process.env.HUAWEI_OBS_BUCKET || "",
        endpoint: process.env.HUAWEI_OBS_ENDPOINT || "",
        error: "Object storage unavailable. See server logs for details.",
      });
    }
  }));

  // ---------- Object storage: signed uploads / downloads ----------
  const SignUploadBody = z.object({
    namespace: z.string().min(1),
    fileName: z.string().min(1).max(256),
    mime: z.string().min(1).max(128).optional(),
    sizeBytes: z.number().int().nonnegative().max(MAX_UPLOAD_BYTES),
    // Optional owning entity ID; folded into the storage key so artifacts are
    // grouped per customer/case/etc. For brand-new onboarding flows the UI
    // sends a session-stable "onboarding-{ulid}" until the customer ID exists.
    subjectId: z.string().min(1).max(96).optional(),
  });

  app.post("/api/uploads/sign", requireActor, asyncHandler(async (req, res) => {
    const parsed = SignUploadBody.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid sign payload" });
    }
    const { namespace, fileName, mime, sizeBytes, subjectId } = parsed.data;
    if (!isAllowedNamespace(namespace)) {
      return res.status(400).json({
        error: `Namespace not allowed. Use one of: ${(ALLOWED_NAMESPACES as readonly string[]).filter((n) => n !== "system-health").join(", ")}.`,
      });
    }
    if (namespace === "system-health") {
      return res.status(400).json({ error: "namespace 'system-health' is reserved for internal probes." });
    }
    const ns = namespace as ObjectNamespace;
    const store = getObjectStore();
    const key = generateStorageKey(ns, fileName, subjectId);
    const url = await store.getSignedUploadUrl(key, { expiresInSeconds: 300, contentType: mime });
    res.json({
      key,
      url,
      method: "PUT",
      expiresInSeconds: 300,
      backend: store.backend,
      bucket: store.bucket,
      maxBytes: MAX_UPLOAD_BYTES,
      requiredHeaders: mime ? { "Content-Type": mime } : {},
      sizeBytes,
    });
  }));

  const SignDownloadBody = z.object({
    key: z.string().min(1).max(1024),
    expiresInSeconds: z.number().int().positive().max(3600).optional(),
  });
  // Dev-only: in-memory backend PUT/GET handlers. Real OBS signed URLs PUT
  // straight to Huawei; the in-memory fallback round-trips through the server
  // so the same browser code path works in both modes. The 25MB body limit
  // matches MAX_UPLOAD_BYTES; the namespace allow-list (defence in depth)
  // mirrors /api/uploads/sign.
  const memoryUploadRouter = express.raw({ type: "*/*", limit: MAX_UPLOAD_BYTES });
  app.put("/api/uploads/memory-put/:key", memoryUploadRouter, asyncHandler(async (req, res) => {
    const store = getObjectStore();
    if (store.backend !== "memory") {
      return res.status(400).json({ error: "memory-put only available with in-memory storage backend" });
    }
    const key = decodeURIComponent(req.params.key);
    const prefix = key.split("/")[0];
    if (!prefix || !isAllowedNamespace(prefix) || prefix === "system-health") {
      return res.status(400).json({ error: "Key outside allowed namespaces." });
    }
    const body = req.body as Buffer | undefined;
    if (!Buffer.isBuffer(body) || body.length === 0) {
      return res.status(400).json({ error: "Empty body" });
    }
    await store.putObject({ key, body, contentType: req.header("content-type") || undefined });
    res.json({ ok: true, key, sizeBytes: body.length });
  }));
  app.get("/api/uploads/memory-get/:key", asyncHandler(async (req, res) => {
    const store = getObjectStore();
    if (store.backend !== "memory") {
      return res.status(400).json({ error: "memory-get only available with in-memory storage backend" });
    }
    const key = decodeURIComponent(req.params.key);
    const prefix = key.split("/")[0];
    if (!prefix || !isAllowedNamespace(prefix) || prefix === "system-health") {
      return res.status(400).json({ error: "Key outside allowed namespaces." });
    }
    const meta = await store.headObject(key);
    if (!meta) return res.status(404).json({ error: "Not found" });
    const body = await store.getObject(key);
    if (meta.contentType) res.setHeader("Content-Type", meta.contentType);
    res.send(body);
  }));

  app.post("/api/uploads/sign-download", requireActor, asyncHandler(async (req, res) => {
    const parsed = SignDownloadBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid payload" });
    const { key, expiresInSeconds } = parsed.data;
    // Restrict to keys under our allow-listed namespaces (defence in depth).
    const prefix = key.split("/")[0];
    if (!prefix || !isAllowedNamespace(prefix) || prefix === "system-health") {
      return res.status(400).json({ error: "Key outside allowed namespaces." });
    }
    const url = await getObjectStore().getSignedDownloadUrl(key, { expiresInSeconds: expiresInSeconds ?? 300 });
    res.json({ key, url, method: "GET", expiresInSeconds: expiresInSeconds ?? 300 });
  }));

  // ---------- Customers ----------
  // Hydrates each customer row with its `documents[]` so the UI's drawers
  // and Documents tabs can render straight off `/api/customers`. Documents
  // are fetched in a single round-trip and grouped in memory.
  app.get("/api/customers", requireDb, asyncHandler(async (_req, res) => {
    const storage = getStorage();
    const [rows, allDocs] = await Promise.all([
      storage.listCustomers(),
      storage.listAllCustomerDocuments(),
    ]);
    const byCustomer = new Map<string, typeof allDocs>();
    for (const d of allDocs) {
      const arr = byCustomer.get(d.customerId);
      if (arr) arr.push(d);
      else byCustomer.set(d.customerId, [d]);
    }
    res.json(rows.map(r => ({ ...r, documents: byCustomer.get(r.id) ?? [] })));
  }));

  app.get("/api/customers/aggregates", requireDb, asyncHandler(async (_req, res) => {
    res.json(await getStorage().getCustomerAggregates());
  }));

  app.get("/api/customers/:id", requireDb, asyncHandler(async (req, res) => {
    const storage = getStorage();
    const c = await storage.getCustomer(req.params.id);
    if (!c) return res.status(404).json({ error: "Customer not found" });
    const documents = await storage.listCustomerDocuments(req.params.id);
    res.json({ ...c, documents });
  }));

  app.post("/api/customers", requireDb, requireActor, asyncHandler(async (req, res) => {
    const parsed = CreateCustomerBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid customer payload" });
    const created = await getStorage().createCustomer(
      parsed.data.customer,
      parsed.data.documents.map(d => ({ ...d, customerId: parsed.data.customer.id })),
    );
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "customer.create",
      targetType: "customer",
      targetId: created.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: { displayName: created.displayName, type: created.type },
    });
    res.status(201).json(created);
  }));

  app.get("/api/customers/:id/documents", requireDb, asyncHandler(async (req, res) => {
    res.json(await getStorage().listCustomerDocuments(req.params.id));
  }));

  // ---------- Compliance read-only listings ----------
  app.get("/api/screening", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listScreening())));
  app.get("/api/regulatory-reports", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listRegulatoryReports())));
  app.get("/api/fraud-register", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listFraudRegister())));
  app.get("/api/edd-cases", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listEddCases())));
  app.get("/api/alerts", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listAlerts())));
  app.get("/api/cases", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listCases())));

  // ---------- Alerts (single + writes) ----------
  app.get("/api/alerts/:id", requireDb, asyncHandler(async (req, res) => {
    const a = await getStorage().getAlert(req.params.id);
    if (!a) return res.status(404).json({ error: "Alert not found" });
    res.json(a);
  }));

  app.post("/api/alerts", requireDb, requireActor, requirePermission("manage_alerts"), asyncHandler(async (req, res) => {
    const parsed = insertAlertSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid alert payload" });
    try {
      const created = await getStorage().createAlert(parsed.data);
      res.status(201).json(created);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (msg.includes("duplicate key")) return res.status(409).json({ error: "Alert with that id already exists" });
      throw e;
    }
  }));

  const PatchAlertSchema = insertAlertSchema.partial().omit({ id: true });
  app.patch("/api/alerts/:id", requireDb, requireActor, requirePermission("manage_alerts"), asyncHandler(async (req, res) => {
    const parsed = PatchAlertSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid alert patch" });
    const updated = await getStorage().updateAlert(req.params.id, parsed.data);
    if (!updated) return res.status(404).json({ error: "Alert not found" });
    res.json(updated);
  }));

  const AlertNoteSchema = z.object({
    author: z.string().min(1),
    text: z.string().min(1),
    ts: z.string().optional(),
  });
  app.post("/api/alerts/:id/notes", requireDb, requireActor, requirePermission("manage_alerts"), asyncHandler(async (req, res) => {
    const parsed = AlertNoteSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid note payload" });
    const storage = getStorage();
    const alert = await storage.getAlert(req.params.id);
    if (!alert) return res.status(404).json({ error: "Alert not found" });
    const note = { author: parsed.data.author, text: parsed.data.text, ts: parsed.data.ts ?? new Date().toISOString() };
    const nextNotes = [...((alert.notes as unknown[]) ?? []), note];
    const updated = await storage.updateAlert(req.params.id, { notes: nextNotes } as never);
    res.status(201).json(updated);
  }));

  // ---------- Cases (single + writes) ----------
  app.get("/api/cases/:id", requireDb, asyncHandler(async (req, res) => {
    const c = await getStorage().getCase(req.params.id);
    if (!c) return res.status(404).json({ error: "Case not found" });
    res.json(c);
  }));

  app.post("/api/cases", requireDb, requireActor, requirePermission("create_cases"), asyncHandler(async (req, res) => {
    const parsed = insertCaseSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid case payload" });
    try {
      const created = await getStorage().createCase(parsed.data);
      res.status(201).json(created);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (msg.includes("duplicate key")) return res.status(409).json({ error: "Case with that id already exists" });
      throw e;
    }
  }));

  const PatchCaseSchema = insertCaseSchema.partial().omit({ id: true });
  app.patch("/api/cases/:id", requireDb, requireActor, requirePermission("manage_cases"), asyncHandler(async (req, res) => {
    const parsed = PatchCaseSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid case patch" });
    const updated = await getStorage().updateCase(req.params.id, parsed.data);
    if (!updated) return res.status(404).json({ error: "Case not found" });
    res.json(updated);
  }));

  // Generic JSONB-array appender for case notes/timeline/entities/evidence.
  // Accepts an arbitrary JSON object; the server stamps an id/timestamp when missing
  // and persists the appended array via updateCase. Matches the rules audit pattern.
  // Per-field zod schemas for case JSONB appenders. Each row in
  // notes/timeline/linkedEntities/evidence must conform to the shape the UI
  // and PDF/CSV exporters rely on; arbitrary objects could break renderers.
  const CaseNoteAppendSchema = z.object({
    id: z.string().optional(),
    caseId: z.string().optional(),
    authorId: z.string().min(1),
    authorName: z.string().min(1),
    content: z.string().min(1),
    timestamp: z.string().optional(),
    type: z.enum(["comment", "evidence", "action_taken"]),
    mentions: z.array(z.string()).optional(),
  }).passthrough();
  const CaseTimelineAppendSchema = z.object({
    id: z.string().optional(),
    type: z.string().min(1),
    title: z.string().min(1),
    description: z.string(),
    performedBy: z.string().min(1),
    timestamp: z.string().optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
  }).passthrough();
  const CaseEntityAppendSchema = z.object({
    id: z.string().optional(),
    type: z.enum(["vendor", "employee", "contract", "invoice", "account", "customer"]),
    name: z.string().min(1),
    reference: z.string().min(1),
    relationship: z.string().min(1),
    addedBy: z.string().min(1),
    addedAt: z.string().optional(),
    notes: z.string().optional(),
    riskIndicator: z.enum(["low", "medium", "high", "critical"]).optional(),
  }).passthrough();
  const CaseEvidenceAppendSchema = z.object({
    id: z.string().optional(),
    caseId: z.string().optional(),
    fileName: z.string().min(1),
    fileType: z.string().min(1),
    fileSize: z.number().int().nonnegative(),
    mimeType: z.string().min(1),
    source: z.string().min(1),
    sourceAttribution: z.string().min(1),
    tags: z.array(z.string()),
    description: z.string(),
    uploadedBy: z.string().min(1),
    uploadedAt: z.string().optional(),
    // Required after the OBS migration: every evidence row must reference a
    // real object in the `case-evidence/` namespace. Orphaned metadata-only
    // rows are rejected (see headObject check in the handler below).
    storageKey: z.string().min(1).max(1024),
    custodyChain: z.array(z.object({
      action: z.string(),
      performedBy: z.string(),
      timestamp: z.string(),
      details: z.string().optional(),
    })),
  }).passthrough();
  const APPEND_SCHEMAS = {
    notes: CaseNoteAppendSchema,
    timeline: CaseTimelineAppendSchema,
    linkedEntities: CaseEntityAppendSchema,
    evidence: CaseEvidenceAppendSchema,
  } as const;

  function makeCaseAppender(field: "notes" | "timeline" | "linkedEntities" | "evidence") {
    return asyncHandler(async (req: Request, res: Response) => {
      const parsed = APPEND_SCHEMAS[field].safeParse(req.body);
      if (!parsed.success) {
        return res.status(400).json({ error: parsed.error.issues[0]?.message || `Invalid ${field} entry` });
      }
      const entry: Record<string, unknown> = {
        ...(parsed.data as Record<string, unknown>),
        id: (parsed.data as { id?: string }).id ?? `${field}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        timestamp: (parsed.data as { timestamp?: string }).timestamp ?? new Date().toISOString(),
      };
      const updated = await getStorage().appendCaseArray(req.params.id, field, entry);
      if (!updated) return res.status(404).json({ error: "Case not found" });
      res.status(201).json(updated);
    });
  }
  app.post("/api/cases/:id/notes", requireDb, requireActor, requirePermission("manage_cases"), makeCaseAppender("notes"));
  app.post("/api/cases/:id/timeline", requireDb, requireActor, requirePermission("manage_cases"), makeCaseAppender("timeline"));
  app.post("/api/cases/:id/entities", requireDb, requireActor, requirePermission("manage_cases"), makeCaseAppender("linkedEntities"));

  // Evidence has stricter requirements than the other JSONB appenders:
  // (1) the storageKey MUST live under the `case-evidence/` namespace and
  // (2) the underlying OBS object MUST exist (headObject) — this enforces
  // the "no orphaned metadata-only entries" rule and gives investigators a
  // real chain-of-custody artifact. We also stamp an "uploaded" custody-chain
  // entry server-side that records the OBS key so the timeline cannot drift
  // from the actual stored bytes.
  app.post("/api/cases/:id/evidence", requireDb, requireActor, requirePermission("manage_cases"), asyncHandler(async (req: Request, res: Response) => {
    const parsed = CaseEvidenceAppendSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid evidence entry" });
    }
    const { storageKey } = parsed.data;
    const prefix = storageKey.split("/")[0];
    if (prefix !== "case-evidence") {
      return res.status(400).json({ error: "storageKey must live under the 'case-evidence/' namespace." });
    }
    const store = getObjectStore();
    let head;
    try {
      head = await store.headObject(storageKey);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[case-evidence] headObject failed:", msg);
      return res.status(502).json({ error: "Object storage unavailable — could not verify uploaded file." });
    }
    if (!head) {
      return res.status(409).json({
        error: "Uploaded file not found in object storage. Re-upload before submitting.",
      });
    }

    const now = new Date().toISOString();
    const incomingChain = (parsed.data.custodyChain ?? []) as Array<{ action: string; performedBy: string; timestamp: string; details?: string }>;
    // Always append a server-stamped 'uploaded' entry that records the OBS
    // key so the chain-of-custody trail is verifiable against the bucket.
    const custodyChain = [
      ...incomingChain,
      {
        action: "uploaded",
        performedBy: parsed.data.uploadedBy,
        timestamp: now,
        details: `Stored in OBS at ${storageKey}${typeof head.sizeBytes === "number" ? ` (${head.sizeBytes} bytes)` : ""}`,
      },
    ];
    const entry: Record<string, unknown> = {
      ...(parsed.data as Record<string, unknown>),
      // Trust the bucket for size/mime — clients can lie.
      fileSize: head.sizeBytes ?? parsed.data.fileSize,
      mimeType: head.contentType || parsed.data.mimeType,
      custodyChain,
      id: parsed.data.id ?? `evidence-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      uploadedAt: parsed.data.uploadedAt ?? now,
    };
    const updated = await getStorage().appendCaseArray(req.params.id, "evidence", entry);
    if (!updated) return res.status(404).json({ error: "Case not found" });
    res.status(201).json(updated);
  }));

  // Extract Postgres SQLSTATE code from a Drizzle/pg error chain.
  // Drizzle wraps the original pg error and exposes it via `.cause`.
  function pgErrorCode(err: unknown): string | undefined {
    let cur: unknown = err;
    for (let i = 0; i < 5 && cur; i++) {
      if (typeof cur === "object" && cur !== null && "code" in cur) {
        const c = (cur as { code?: unknown }).code;
        if (typeof c === "string") return c;
      }
      cur = (cur as { cause?: unknown })?.cause;
    }
    return undefined;
  }

  // ---------- Regulatory Reports (STR/CTR) ----------
  // Reuse the shared drizzle-zod insert schemas as the source of truth, then
  // override timestamp columns with an ISO-string transform — drizzle-zod
  // emits z.date() for timestamp cols, but JSON only carries strings.
  const isoDate = z.string().min(1).transform((s, ctx) => {
    const d = new Date(s);
    if (isNaN(d.getTime())) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Invalid ISO date" });
      return z.NEVER;
    }
    return d;
  });

  // We can't .extend() insertRegulatoryReportSchema directly: drizzle-zod ships
  // its own Zod instance, so cross-instance .extend() rejects the override
  // schemas at runtime. Instead we hand-roll the shape and assert at *type*
  // level that the output assigns to InsertRegulatoryReport, so any drift
  // between the table schema and this validator is a TS error.
  const reportStatus = z.enum(["draft", "pending_review", "submitted", "acknowledged", "rejected"]);
  const reportType = z.enum(["STR", "CTR"]);
  const customerType = z.enum(["individual", "business"]);
  const CreateReportSchema = z.object({
    id: z.string().min(1),
    type: reportType,
    customerId: z.string().min(1),
    customerName: z.string().min(1),
    customerType: customerType,
    amount: z.number().nonnegative(),
    currency: z.string().min(1).default("NGN"),
    transactionIds: z.array(z.string()).default([]),
    reason: z.string().min(1),
    narrative: z.string().min(1),
    status: reportStatus.default("draft"),
    deadline: isoDate,
    submittedAt: isoDate.optional(),
    acknowledgedAt: isoDate.optional(),
    submittedBy: z.string().optional(),
    preparedBy: z.string().min(1),
    reviewedBy: z.string().optional(),
    attachments: z.number().int().nonnegative().default(0),
    flagsTriggered: z.array(z.string()).default([]),
    jurisdiction: z.string().min(1).default("NG"),
    regulatoryRef: z.string().optional(),
  });
  // Compile-time guarantee the validator shape stays compatible with the
  // shared drizzle insert type. If the table grows a required column, this
  // assignment will fail TS.
  type _AssertReportShape = z.infer<typeof CreateReportSchema> extends Partial<z.infer<typeof insertRegulatoryReportSchema>> ? true : never;
  const _r: _AssertReportShape = true; void _r;
  const PatchReportSchema = z.object({
    type: reportType.optional(),
    amount: z.number().nonnegative().optional(),
    currency: z.string().min(1).optional(),
    transactionIds: z.array(z.string()).optional(),
    reason: z.string().min(1).optional(),
    narrative: z.string().min(1).optional(),
    status: reportStatus.optional(),
    deadline: isoDate.optional(),
    submittedAt: isoDate.optional(),
    acknowledgedAt: isoDate.optional(),
    submittedBy: z.string().nullable().optional(),
    reviewedBy: z.string().nullable().optional(),
    regulatoryRef: z.string().nullable().optional(),
    flagsTriggered: z.array(z.string()).optional(),
    attachments: z.number().int().nonnegative().optional(),
  });

  app.get("/api/regulatory-reports/:id", requireDb, asyncHandler(async (req, res) => {
    const r = await getStorage().getRegulatoryReport(req.params.id);
    if (!r) return res.status(404).json({ error: "Report not found" });
    res.json(r);
  }));

  app.post("/api/regulatory-reports", requireDb, requireActor, requirePermission("file_reports"), asyncHandler(async (req, res) => {
    const parsed = CreateReportSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid report payload" });
    try {
      const created = await getStorage().createRegulatoryReport(parsed.data);
      res.status(201).json(created);
    } catch (e) {
      const code = pgErrorCode(e);
      if (code === "23505") return res.status(409).json({ error: "Report with that id already exists" });
      if (code === "23503") return res.status(400).json({ error: `Unknown customerId: ${parsed.data.customerId}` });
      throw e;
    }
  }));

  app.patch("/api/regulatory-reports/:id", requireDb, requireActor, requirePermission("file_reports"), asyncHandler(async (req, res) => {
    const parsed = PatchReportSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid report patch" });
    const updated = await getStorage().updateRegulatoryReport(req.params.id, parsed.data as Record<string, unknown>);
    if (!updated) return res.status(404).json({ error: "Report not found" });
    res.json(updated);
  }));

  // Replace or merge linked transaction IDs on an existing report.
  const ReportTxnsSchema = z.object({
    transactionIds: z.array(z.string().min(1)).min(1).max(500),
    mode: z.enum(["replace", "append"]).default("append"),
  });
  app.post("/api/regulatory-reports/:id/transactions", requireDb, requireActor, requirePermission("file_reports"), asyncHandler(async (req, res) => {
    const parsed = ReportTxnsSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid transactions payload" });
    const storage = getStorage();
    const existing = await storage.getRegulatoryReport(req.params.id);
    if (!existing) return res.status(404).json({ error: "Report not found" });
    const next = parsed.data.mode === "replace"
      ? parsed.data.transactionIds
      : Array.from(new Set([...(existing.transactionIds ?? []), ...parsed.data.transactionIds]));
    const updated = await storage.updateRegulatoryReport(req.params.id, { transactionIds: next });
    res.status(201).json(updated);
  }));

  // ---------- Fraud Register ----------
  // Same reasoning as CreateReportSchema above: hand-rolled validator with a
  // type-level assertion that the shape stays compatible with InsertFraudRegister.
  const fraudStatus = z.enum(["open", "investigating", "recovered", "written_off", "closed"]);
  const fraudType = z.enum([
    "card_fraud", "wire_fraud", "identity_theft", "phishing", "account_takeover",
    "merchant_fraud", "mule_account", "cheque_fraud", "sim_swap",
  ]);
  const CreateFraudSchema = z.object({
    id: z.string().min(1),
    incidentDate: isoDate,
    reportedDate: isoDate,
    customerId: z.string().min(1),
    customerName: z.string().min(1),
    accountNumber: z.string().min(1),
    fraudType: fraudType,
    channel: z.string().min(1),
    amountLost: z.number().nonnegative().default(0),
    amountSaved: z.number().nonnegative().default(0),
    amountRecovered: z.number().nonnegative().default(0),
    status: fraudStatus.default("open"),
    description: z.string().min(1),
    perpetrator: z.string().optional(),
    linkedAccounts: z.array(z.string()).default([]),
    linkedCases: z.array(z.string()).default([]),
    resolutionNotes: z.string().optional(),
    reportedToCbn: z.boolean().default(false),
    reportedToNibss: z.boolean().default(false),
    reportedToNfiu: z.boolean().default(false),
    assignedTo: z.string().min(1),
    closedAt: isoDate.optional(),
  });
  type _AssertFraudShape = z.infer<typeof CreateFraudSchema> extends Partial<z.infer<typeof insertFraudRegisterSchema>> ? true : never;
  const _f: _AssertFraudShape = true; void _f;
  const PatchFraudSchema = z.object({
    fraudType: fraudType.optional(),
    channel: z.string().min(1).optional(),
    amountLost: z.number().nonnegative().optional(),
    amountSaved: z.number().nonnegative().optional(),
    amountRecovered: z.number().nonnegative().optional(),
    status: fraudStatus.optional(),
    description: z.string().min(1).optional(),
    perpetrator: z.string().nullable().optional(),
    linkedAccounts: z.array(z.string()).optional(),
    linkedCases: z.array(z.string()).optional(),
    resolutionNotes: z.string().nullable().optional(),
    reportedToCbn: z.boolean().optional(),
    reportedToNibss: z.boolean().optional(),
    reportedToNfiu: z.boolean().optional(),
    assignedTo: z.string().min(1).optional(),
    closedAt: isoDate.nullable().optional(),
  });
  const FraudTimelineAppendSchema = z.object({
    id: z.string().optional(),
    type: z.string().min(1),
    title: z.string().min(1),
    description: z.string().optional(),
    performedBy: z.string().min(1),
    timestamp: z.string().optional(),
  });

  app.get("/api/fraud-register/:id", requireDb, asyncHandler(async (req, res) => {
    const r = await getStorage().getFraudRegisterEntry(req.params.id);
    if (!r) return res.status(404).json({ error: "Fraud incident not found" });
    res.json(r);
  }));

  app.post("/api/fraud-register", requireDb, requireActor, requirePermission("log_fraud_incident"), asyncHandler(async (req, res) => {
    const parsed = CreateFraudSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid fraud payload" });
    try {
      const created = await getStorage().createFraudRegisterEntry(parsed.data);
      res.status(201).json(created);
    } catch (e) {
      const code = pgErrorCode(e);
      if (code === "23505") return res.status(409).json({ error: "Fraud entry with that id already exists" });
      if (code === "23503") return res.status(400).json({ error: `Unknown customerId: ${parsed.data.customerId}` });
      throw e;
    }
  }));

  app.patch("/api/fraud-register/:id", requireDb, requireActor, requirePermission("log_fraud_incident"), asyncHandler(async (req, res) => {
    const parsed = PatchFraudSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid fraud patch" });
    const updated = await getStorage().updateFraudRegisterEntry(req.params.id, parsed.data as Record<string, unknown>);
    if (!updated) return res.status(404).json({ error: "Fraud incident not found" });
    res.json(updated);
  }));

  app.post("/api/fraud-register/:id/timeline", requireDb, requireActor, requirePermission("log_fraud_incident"), asyncHandler(async (req, res) => {
    const parsed = FraudTimelineAppendSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid timeline entry" });
    const entry = {
      ...parsed.data,
      id: parsed.data.id ?? `ftl-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      timestamp: parsed.data.timestamp ?? new Date().toISOString(),
    };
    const updated = await getStorage().appendFraudTimeline(req.params.id, entry);
    if (!updated) return res.status(404).json({ error: "Fraud incident not found" });
    res.status(201).json(updated);
  }));
  // ---------- Transactions ----------
  const txnRiskLevel = z.enum(["low", "medium", "high", "critical"]);
  const txnStatus = z.enum(["completed", "pending", "declined", "reversed"]);
  const txnType = z.enum(["credit_card", "wire_transfer", "ach", "mobile", "atm"]);
  const txnChannel = z.enum(["pos", "mobile", "web", "atm", "branch"]);
  const CreateTransactionSchema = z.object({
    id: z.string().min(1),
    customerId: z.string().min(1),
    accountId: z.string().default(""),
    amount: z.number(),
    currency: z.string().default("NGN"),
    type: txnType.default("mobile"),
    merchantId: z.string().default(""),
    merchantName: z.string().default(""),
    merchantCategoryCode: z.string().default(""),
    channel: txnChannel.default("mobile"),
    deviceId: z.string().default(""),
    ipAddress: z.string().default(""),
    geoLocation: z.object({
      latitude: z.number(),
      longitude: z.number(),
      country: z.string(),
      city: z.string(),
    }).nullable().optional(),
    cardNumberMasked: z.string().default(""),
    status: txnStatus.default("completed"),
    beneficiaryId: z.string().nullable().optional(),
    beneficiaryAccount: z.string().nullable().optional(),
    description: z.string().default(""),
    riskScore: z.number().int().default(0),
    riskLevel: txnRiskLevel.default("low"),
    mlProbability: z.number().default(0),
    anomalyScore: z.number().default(0),
    rulesTriggered: z.array(z.string()).default([]),
    timestamp: z.string().refine(
      v => !Number.isNaN(new Date(v).getTime()),
      { message: "timestamp must be a valid date string" },
    ).optional(),
  });
  type _AssertTxnShape = z.infer<typeof CreateTransactionSchema> extends Partial<z.infer<typeof insertTransactionSchema>> ? true : never;
  const _t: _AssertTxnShape = true; void _t;

  app.get("/api/transactions", requireDb, asyncHandler(async (req, res) => {
    const q = req.query;
    const num = (v: unknown): number | undefined => {
      if (typeof v !== "string" || v.trim() === "") return undefined;
      const n = Number(v);
      return Number.isFinite(n) ? n : undefined;
    };
    const str = (v: unknown): string | undefined =>
      typeof v === "string" && v.trim() !== "" ? v : undefined;
    let since: Date | undefined;
    if (typeof q.since === "string" && q.since.trim() !== "") {
      const d = new Date(q.since);
      if (!isNaN(d.getTime())) since = d;
    }
    const filters: TransactionFilters = {
      customerId: str(q.customerId),
      search: str(q.search),
      type: str(q.type),
      status: str(q.status),
      riskLevel: str(q.riskLevel),
      riskMin: num(q.riskMin),
      riskMax: num(q.riskMax),
      since,
      limit: num(q.limit),
    };
    res.json(await getStorage().listTransactions(filters));
  }));

  app.get("/api/transactions/sample", requireDb, asyncHandler(async (req, res) => {
    const sizeRaw = req.query.size;
    const daysRaw = req.query.windowDays;
    const size = typeof sizeRaw === "string" && sizeRaw.trim() !== "" ? Number(sizeRaw) : 500;
    const sinceDays = typeof daysRaw === "string" && daysRaw.trim() !== "" ? Number(daysRaw) : undefined;
    res.json(await getStorage().sampleTransactions({
      size: Number.isFinite(size) ? size : 500,
      sinceDays: typeof sinceDays === "number" && Number.isFinite(sinceDays) ? sinceDays : undefined,
    }));
  }));

  app.get("/api/transactions/hourly", requireDb, asyncHandler(async (req, res) => {
    const raw = req.query.hours;
    const hours = typeof raw === "string" && raw.trim() !== "" ? Number(raw) : 24;
    res.json(await getStorage().getTransactionsHourly(Number.isFinite(hours) ? hours : 24));
  }));

  app.get("/api/transactions/:id", requireDb, asyncHandler(async (req, res) => {
    const r = await getStorage().getTransaction(req.params.id);
    if (!r) return res.status(404).json({ error: "Transaction not found" });
    res.json(r);
  }));

  app.post("/api/transactions", requireDb, asyncHandler(async (req, res) => {
    const parsed = CreateTransactionSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid transaction payload" });
    try {
      const { timestamp, ...rest } = parsed.data;
      const row = {
        ...rest,
        ...(timestamp ? { timestamp: new Date(timestamp) } : {}),
      } as Parameters<ReturnType<typeof getStorage>["createTransaction"]>[0];
      const created = await getStorage().createTransaction(row);
      res.status(201).json(created);
    } catch (e) {
      const code = pgErrorCode(e);
      if (code === "23505") return res.status(409).json({ error: "Transaction with that id already exists" });
      if (code === "23503") return res.status(400).json({ error: `Unknown customerId: ${parsed.data.customerId}` });
      throw e;
    }
  }));

  // ---------- Users / IAM ----------
  app.get("/api/users", requireDb, requireActor, asyncHandler(async (_req, res) => {
    const rows = await getStorage().listUsers();
    res.json(rows.map((u) => sanitizeUser(u as unknown as Record<string, unknown>)));
  }));

  // ---------- Current-user permissions (Task #46) ----------
  // NOTE: Both routes below MUST be registered before `/api/users/:id` so
  // they aren't shadowed by the dynamic param matcher.
  // `/me/permissions` returns the union of permissionKeys derived from the
  // acting user's role assignments. The client `usePermissions()` hook
  // consumes this to hide/disable buttons; server-side `requirePermission()`
  // is the source of truth and gates the actual mutations.
  app.get("/api/users/me/permissions", requireDb, requireActor, asyncHandler(async (req, res) => {
    const id = getActorUserId(req)!;
    const { user, permissions } = await resolveActorPermissions(id);
    if (!user) return res.status(404).json({ error: "Actor user not found." });
    res.json({ userId: user.id, name: user.name, roles: user.roles, permissions: Array.from(permissions).sort() });
  }));

  // ---------- Auth (Task #48): real session-cookie login ----------
  const LoginBody = z.object({
    email: z.string().min(1),
    password: z.string().min(1),
  });

  app.post("/api/auth/login", requireDb, asyncHandler(async (req, res) => {
    const parsed = LoginBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: "Email and password are required." });
    const email = parsed.data.email.trim().toLowerCase();
    const all = await getStorage().listUsers();
    const user = all.find((u) => (u.email || "").toLowerCase() === email);
    // Generic error message: don't leak whether email exists.
    const generic = { error: "Invalid email or password." };
    if (!user) return res.status(401).json(generic);
    if (user.isActive === false || user.status === "suspended" || user.status === "deactivated") {
      return res.status(403).json({ error: "Account is not active. Contact your administrator." });
    }
    if (!user.passwordHash || !verifyPassword(parsed.data.password, user.passwordHash)) {
      return res.status(401).json(generic);
    }
    setSessionCookie(res, user.id);
    const ip = req.ip || req.socket.remoteAddress || null;
    // Best-effort: stamp last-login fields and append an audit entry.
    try {
      await getStorage().updateUser(user.id, {
        lastLogin: new Date(),
        lastLoginIp: ip || undefined,
      } as never);
    } catch { /* ignore */ }
    await getStorage().appendAudit({
      actorUserId: user.id,
      actorName: user.name,
      action: "auth.login",
      targetType: "user",
      targetId: user.id,
      ipAddress: ip,
      metadata: null,
    });
    const { user: meUser, permissions } = await resolveActorPermissions(user.id);
    res.json({
      userId: user.id,
      email: user.email,
      name: user.name,
      roles: meUser?.roles ?? [],
      permissions: Array.from(permissions).sort(),
    });
  }));

  app.post("/api/auth/logout", asyncHandler(async (req, res) => {
    const id = getActorUserId(req);
    clearSessionCookie(res);
    if (id && isDbConfigured()) {
      try {
        const u = await getStorage().getUser(id);
        if (u) {
          await getStorage().appendAudit({
            actorUserId: id,
            actorName: u.name,
            action: "auth.logout",
            targetType: "user",
            targetId: id,
            ipAddress: req.ip || req.socket.remoteAddress || null,
            metadata: null,
          });
        }
      } catch { /* ignore */ }
    }
    res.json({ ok: true });
  }));

  app.get("/api/auth/me", asyncHandler(async (req, res) => {
    const id = getActorUserId(req);
    if (!id) return res.status(401).json({ error: "Not signed in." });
    if (!isDbConfigured()) return res.status(503).json({ error: "Database not configured." });
    const { user, permissions } = await resolveActorPermissions(id);
    if (!user) {
      // Stale cookie referencing a deleted user — clear it.
      clearSessionCookie(res);
      return res.status(401).json({ error: "Session user no longer exists." });
    }
    const u = await getStorage().getUser(id);
    res.json({
      userId: user.id,
      email: u?.email ?? "",
      name: user.name,
      roles: user.roles,
      permissions: Array.from(permissions).sort(),
    });
  }));

  // Allow signed-in users to set/change their own password (one-shot for
  // demo accounts whose default seeded password should be rotated). Admins
  // can change anyone's via PATCH /api/users/:id with a `password` field.
  const ChangePasswordBody = z.object({
    currentPassword: z.string().min(1).optional(),
    newPassword: z.string().min(8),
  });
  app.post("/api/auth/change-password", requireDb, requireActor, asyncHandler(async (req, res) => {
    const parsed = ChangePasswordBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid payload" });
    const id = getActorUserId(req)!;
    const u = await getStorage().getUser(id);
    if (!u) return res.status(404).json({ error: "User not found." });
    if (u.passwordHash) {
      if (!parsed.data.currentPassword || !verifyPassword(parsed.data.currentPassword, u.passwordHash)) {
        return res.status(401).json({ error: "Current password is incorrect." });
      }
    }
    await getStorage().updateUser(id, {
      passwordHash: hashPassword(parsed.data.newPassword),
      passwordUpdatedAt: new Date(),
    } as never);
    await getStorage().appendAudit({
      actorUserId: id,
      actorName: u.name,
      action: "auth.password_change",
      targetType: "user",
      targetId: id,
      ipAddress: req.ip || req.socket.remoteAddress || null,
      metadata: null,
    });
    res.json({ ok: true });
  }));

  // Returns the canonical demo accounts used by the header user-switcher
  // (one per business role). Filtered by id prefix `USR-DEMO-` so it
  // can't leak the full user list.
  app.get("/api/users/demo-accounts", requireDb, asyncHandler(async (_req, res) => {
    const all = await getStorage().listUsers();
    const demos = all
      .filter((u) => u.id.startsWith("USR-DEMO-"))
      .map((u) => ({
        id: u.id,
        email: u.email,
        name: u.name,
        role: ((u.roles as string[] | null)?.[0]) ?? u.role,
        title: u.title,
        department: u.department,
      }));
    res.json(demos);
  }));

  app.get("/api/users/:id", requireDb, requireActor, asyncHandler(async (req, res) => {
    const u = await getStorage().getUser(req.params.id);
    if (!u) return res.status(404).json({ error: "User not found" });
    res.json(sanitizeUser(u as unknown as Record<string, unknown>));
  }));

  app.post("/api/users", requireDb, requireActor, requirePermission("manage_users"), asyncHandler(async (req, res) => {
    const parsed = CreateUserBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid user payload" });
    const id = parsed.data.id || `USR-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    const created = await getStorage().createUser({ ...parsed.data, id });
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "user.create",
      targetType: "user",
      targetId: created.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: { email: created.email, name: created.name, roles: created.roles },
    });
    res.status(201).json(sanitizeUser(created as unknown as Record<string, unknown>));
  }));

  app.patch("/api/users/:id", requireDb, requireActor, requirePermission("manage_users"), asyncHandler(async (req, res) => {
    const parsed = UpdateUserBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid user patch" });
    const updated = await getStorage().updateUser(req.params.id, parsed.data);
    if (!updated) return res.status(404).json({ error: "User not found" });
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "user.update",
      targetType: "user",
      targetId: updated.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: { changed: Object.keys(parsed.data) },
    });
    res.json(sanitizeUser(updated as unknown as Record<string, unknown>));
  }));

  // ---------- Roles ----------
  app.get("/api/roles", requireDb, asyncHandler(async (_req, res) => res.json(await getStorage().listRoles())));

  app.post("/api/roles", requireDb, requireActor, requirePermission("manage_roles"), asyncHandler(async (req, res) => {
    const parsed = CreateRoleBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid role payload" });
    const id = parsed.data.id || `ROLE-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    const created = await getStorage().createRole({ ...parsed.data, id });
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "role.create",
      targetType: "role",
      targetId: created.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: { name: created.name, permissionKeys: created.permissionKeys },
    });
    res.status(201).json(created);
  }));

  app.patch("/api/roles/:id", requireDb, requireActor, requirePermission("manage_roles"), asyncHandler(async (req, res) => {
    const parsed = UpdateRoleBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid role patch" });
    const updated = await getStorage().updateRole(req.params.id, parsed.data);
    if (!updated) return res.status(404).json({ error: "Role not found" });
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "role.update",
      targetType: "role",
      targetId: updated.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: { changed: Object.keys(parsed.data) },
    });
    res.json(updated);
  }));

  app.delete("/api/roles/:id", requireDb, requireActor, requirePermission("manage_roles"), asyncHandler(async (req, res) => {
    await getStorage().deleteRole(req.params.id);
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "role.delete",
      targetType: "role",
      targetId: req.params.id,
      ipAddress: actor.ipAddress ?? null,
      metadata: null,
    });
    res.status(204).end();
  }));

  // ---------- Role assignments ----------
  app.get("/api/role-assignments", requireDb, asyncHandler(async (_req, res) => {
    res.json(await getStorage().listAssignments());
  }));

  app.post("/api/users/:userId/roles", requireDb, requireActor, requirePermission("manage_roles"), asyncHandler(async (req, res) => {
    const parsed = AssignRoleBody.safeParse({ ...req.body, userId: req.params.userId });
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid assignment" });
    const created = await getStorage().assignRole(parsed.data);
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "user.role.assign",
      targetType: "user",
      targetId: parsed.data.userId,
      ipAddress: actor.ipAddress ?? null,
      metadata: { roleId: parsed.data.roleId },
    });
    res.status(201).json(created);
  }));

  app.delete("/api/users/:userId/roles/:roleId", requireDb, requireActor, requirePermission("manage_roles"), asyncHandler(async (req, res) => {
    await getStorage().unassignRole(req.params.userId, req.params.roleId);
    const actor = actorFromReq(req);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: "user.role.unassign",
      targetType: "user",
      targetId: req.params.userId,
      ipAddress: actor.ipAddress ?? null,
      metadata: { roleId: req.params.roleId },
    });
    res.status(204).end();
  }));

  // ---------- Audit log ----------
  app.get("/api/audit-log", requireDb, asyncHandler(async (req, res) => {
    const q = req.query;
    const parseDate = (v: unknown): Date | undefined => {
      if (typeof v !== "string" || !v) return undefined;
      const d = new Date(v);
      return isNaN(d.getTime()) ? undefined : d;
    };
    const parseInt2 = (v: unknown, def: number, max: number): number => {
      if (typeof v !== "string" || !v) return def;
      const n = Number(v);
      if (!Number.isFinite(n)) return def;
      return Math.min(max, Math.max(0, Math.trunc(n)));
    };
    const result = await getStorage().listAuditLog({
      actorUserId: typeof q.actor === "string" && q.actor ? q.actor : undefined,
      targetType: typeof q.targetType === "string" && q.targetType ? q.targetType : undefined,
      targetId: typeof q.target === "string" && q.target ? q.target : undefined,
      since: parseDate(q.since),
      until: parseDate(q.until),
      limit: parseInt2(q.limit, 100, 500),
      offset: parseInt2(q.offset, 0, 100_000),
    });
    res.json(result);
  }));

  app.post("/api/audit-log", requireDb, requireActor, asyncHandler(async (req, res) => {
    const parsed = z.object({
      action: z.string().min(1),
      targetType: z.string().optional().default(""),
      targetId: z.string().optional().default(""),
      metadata: z.record(z.string(), z.unknown()).nullable().optional(),
    }).safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid audit entry" });
    const actor = actorFromReq(req);
    const created = await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: parsed.data.action,
      targetType: parsed.data.targetType || "",
      targetId: parsed.data.targetId || "",
      ipAddress: actor.ipAddress ?? null,
      metadata: parsed.data.metadata ?? null,
    });
    res.status(201).json(created);
  }));

  // ---------- Customer actions / activity ----------
  app.get("/api/customers/:id/actions", requireDb, asyncHandler(async (req, res) => {
    const raw = req.query.limit;
    let limit = 50;
    if (typeof raw === "string" && raw.trim() !== "") {
      const n = Number(raw);
      if (Number.isFinite(n)) limit = Math.min(200, Math.max(1, Math.trunc(n)));
    }
    res.json(await getStorage().listCustomerActions(req.params.id, limit));
  }));

  app.post("/api/customers/:id/actions", requireDb, requireActor, asyncHandler(async (req, res) => {
    const actor = actorFromReq(req);
    // Server-resolved actor name overrides any client-supplied `actor` field
    // so the customer-action row and downstream audit entry both reflect the
    // verified signed-in user.
    const parsed = AppendActionBody.safeParse({
      ...req.body,
      customerId: req.params.id,
      actor: actor.actorName,
    });
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid action payload" });
    const created = await getStorage().appendCustomerAction(parsed.data);
    await getStorage().appendAudit({
      actorUserId: actor.actorUserId ?? null,
      actorName: actor.actorName,
      action: `customer.action.${parsed.data.action}`,
      targetType: "customer",
      targetId: parsed.data.customerId,
      ipAddress: actor.ipAddress ?? null,
      metadata: { note: parsed.data.note ?? null, ...(parsed.data.metadata ?? {}) },
    });
    res.status(201).json(created);
  }));

  // ---------- Rules ----------
  app.get("/api/rules", requireDb, asyncHandler(async (_req, res) => {
    res.json(await getStorage().listRules());
  }));

  app.get("/api/rules/:id", requireDb, asyncHandler(async (req, res) => {
    const r = await getStorage().getRule(req.params.id);
    if (!r) return res.status(404).json({ error: "Rule not found" });
    res.json(r);
  }));

  app.post("/api/rules", requireDb, requireActor, requirePermission("create_rules"), asyncHandler(async (req, res) => {
    const parsed = insertRuleSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid rule payload" });
    try {
      const created = await getStorage().createRule(parsed.data);
      res.status(201).json(created);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (msg.includes("duplicate key")) return res.status(409).json({ error: "Rule with that id already exists" });
      throw e;
    }
  }));

  const PatchRuleSchema = insertRuleSchema.partial().omit({ id: true });
  app.patch("/api/rules/:id", requireDb, requireActor, requirePermission("edit_rules"), asyncHandler(async (req, res) => {
    const parsed = PatchRuleSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid patch" });
    const updated = await getStorage().updateRule(req.params.id, parsed.data);
    if (!updated) return res.status(404).json({ error: "Rule not found" });
    res.json(updated);
  }));

  app.delete("/api/rules/:id", requireDb, requireActor, requirePermission("delete_rules"), asyncHandler(async (req, res) => {
    const ok = await getStorage().deleteRule(req.params.id);
    if (!ok) return res.status(404).json({ error: "Rule not found" });
    res.status(204).end();
  }));

  // Append a new version to a rule (server bumps currentVersion + appends to versions/auditLog).
  const AddVersionSchema = z.object({
    conditionGroup: z.unknown(),
    actions: z.array(z.unknown()),
    severity: z.string(),
    changedBy: z.string().default("analyst-1"),
    changeNote: z.string().default(""),
    name: z.string().optional(),
    description: z.string().optional(),
    type: z.string().optional(),
    category: z.string().optional(),
    condition: z.string().optional(),
  });
  app.post("/api/rules/:id/versions", requireDb, requireActor, requirePermission("edit_rules"), asyncHandler(async (req, res) => {
    const parsed = AddVersionSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid version payload" });
    const storage = getStorage();
    const rule = await storage.getRule(req.params.id);
    if (!rule) return res.status(404).json({ error: "Rule not found" });
    const now = new Date().toISOString();
    const newVersionNum = rule.currentVersion + 1;
    const versionEntry = {
      version: newVersionNum,
      conditionGroup: parsed.data.conditionGroup,
      actions: parsed.data.actions,
      severity: parsed.data.severity,
      changedBy: parsed.data.changedBy,
      changedAt: now,
      changeNote: parsed.data.changeNote || `Updated rule configuration (v${newVersionNum})`,
    };
    const auditEntry = {
      id: `aud-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      action: "updated" as const,
      performedBy: parsed.data.changedBy,
      timestamp: now,
      details: `Rule updated to version ${newVersionNum}`,
    };
    const patch: Record<string, unknown> = {
      conditionGroup: parsed.data.conditionGroup,
      actions: parsed.data.actions as unknown[],
      severity: parsed.data.severity,
      currentVersion: newVersionNum,
      versions: [...(rule.versions as unknown[]), versionEntry],
      auditLog: [...(rule.auditLog as unknown[]), auditEntry],
    };
    if (parsed.data.name !== undefined) patch.name = parsed.data.name;
    if (parsed.data.description !== undefined) patch.description = parsed.data.description;
    if (parsed.data.type !== undefined) patch.type = parsed.data.type;
    if (parsed.data.category !== undefined) patch.category = parsed.data.category;
    if (parsed.data.condition !== undefined) patch.condition = parsed.data.condition;
    const updated = await storage.updateRule(req.params.id, patch as never);
    res.status(201).json(updated);
  }));

  // Log a simulation result. The actual evaluation is performed client-side
  // (or by a future engine); we just persist the inputs/outputs.
  const SimulateSchema = insertRuleSimulationSchema.omit({ ruleId: true });
  app.post("/api/rules/:id/simulate", requireDb, requireActor, requirePermission("simulate_rules"), asyncHandler(async (req, res) => {
    const parsed = SimulateSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid simulation payload" });
    const storage = getStorage();
    const rule = await storage.getRule(req.params.id);
    // Allow simulations for new (unsaved) rules by passing id="__draft__"
    const ruleId = rule ? rule.id : null;
    const sim = await storage.appendRuleSimulation({ ...parsed.data, ruleId });
    if (rule) {
      const now = new Date().toISOString();
      const auditEntry = {
        id: `aud-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        action: "simulated" as const,
        performedBy: parsed.data.performedBy ?? "analyst-1",
        timestamp: now,
        details: `Simulation: ${parsed.data.matchCount}/${parsed.data.sampleSize} matches (${(parsed.data.hitRate ?? 0).toFixed(1)}% hit rate)`,
      };
      await storage.updateRule(rule.id, { auditLog: [...(rule.auditLog as unknown[]), auditEntry] } as never);
    }
    res.status(201).json(sim);
  }));

  app.get("/api/rules/:id/simulations", requireDb, asyncHandler(async (req, res) => {
    const raw = req.query.limit;
    let limit = 25;
    if (typeof raw === "string" && raw.trim() !== "") {
      const n = Number(raw);
      if (Number.isFinite(n)) limit = Math.min(200, Math.max(1, Math.trunc(n)));
    }
    res.json(await getStorage().listRuleSimulations(req.params.id, limit));
  }));

  // ==========================================================================
  // AI chat sessions — metadata in Postgres, full message JSON in OBS
  // ==========================================================================
  const ChatMessageSchema = z.object({
    role: z.enum(["user", "assistant", "system"]),
    content: z.string(),
    userPrompt: z.string().optional(),
    envelope: z.unknown().optional(),
    isStreaming: z.boolean().optional(),
  });
  const CreateChatSessionSchema = z.object({
    title: z.string().min(1).max(200).optional(),
  });
  const UpdateChatSessionSchema = z.object({
    title: z.string().min(1).max(200).optional(),
    messages: z.array(ChatMessageSchema).max(2000),
  });
  const MAX_CHAT_BYTES = 2 * 1024 * 1024; // 2 MB JSON cap per session

  function deriveTitle(messages: { role: string; content: string }[]): string {
    const first = messages.find(m => m.role === "user")?.content?.trim() ?? "";
    if (!first) return "New chat";
    return first.length > 60 ? first.slice(0, 57) + "…" : first;
  }
  function derivePreview(messages: { role: string; content: string }[]): string {
    const last = messages[messages.length - 1]?.content?.trim() ?? "";
    return last.length > 140 ? last.slice(0, 137) + "…" : last;
  }

  app.get("/api/chat-sessions", requireDb, requireActor, asyncHandler(async (req, res) => {
    const ownerUserId = getActorUserId(req) ?? undefined;
    const limit = (() => {
      const v = req.query.limit;
      if (typeof v !== "string" || !v.trim()) return undefined;
      const n = Number(v);
      return Number.isFinite(n) ? Math.min(200, Math.max(1, Math.trunc(n))) : undefined;
    })();
    res.json(await getStorage().listChatSessions({ ownerUserId, limit }));
  }));

  app.post("/api/chat-sessions", requireDb, requireActor, asyncHandler(async (req, res) => {
    const parsed = CreateChatSessionSchema.safeParse(req.body ?? {});
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid payload" });
    const actor = actorFromReq(req);
    const id = `CHAT-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const store = getObjectStore();
    const storageKey = generateStorageKey("ai-chats", `${id}.json`);
    // Write an empty messages array up-front so subsequent GETs always succeed.
    await store.putObject({ key: storageKey, body: JSON.stringify({ messages: [] }), contentType: "application/json" });
    const created = await getStorage().createChatSession({
      id,
      ownerUserId: actor.actorUserId ?? null,
      ownerName: actor.actorName,
      title: parsed.data.title ?? "New chat",
      storageKey,
      storageBackend: store.backend,
      messageCount: 0,
      lastMessagePreview: "",
    });
    res.status(201).json(created);
  }));

  // Returns 403 when actor is not the owner (defence-in-depth IDOR guard).
  function assertChatOwnership(session: { ownerUserId: string | null }, req: import("express").Request): true | { status: number; error: string } {
    const actorId = getActorUserId(req) ?? "";
    if (session.ownerUserId && actorId && session.ownerUserId !== actorId) {
      return { status: 403, error: "You do not have access to this chat session." };
    }
    return true;
  }

  app.get("/api/chat-sessions/:id", requireDb, requireActor, asyncHandler(async (req, res) => {
    const session = await getStorage().getChatSession(req.params.id);
    if (!session) return res.status(404).json({ error: "Chat session not found" });
    const guard = assertChatOwnership(session, req);
    if (guard !== true) return res.status(guard.status).json({ error: guard.error });
    let messages: unknown[] = [];
    try {
      const buf = await getObjectStore().getObject(session.storageKey);
      const parsed = JSON.parse(buf.toString("utf8"));
      messages = Array.isArray(parsed?.messages) ? parsed.messages : [];
    } catch (e) {
      console.error("[chat-sessions] read OBS failed:", e instanceof Error ? e.message : e);
    }
    res.json({ session, messages });
  }));

  app.put("/api/chat-sessions/:id", requireDb, requireActor, asyncHandler(async (req, res) => {
    const parsed = UpdateChatSessionSchema.safeParse(req.body ?? {});
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid payload" });
    const session = await getStorage().getChatSession(req.params.id);
    if (!session) return res.status(404).json({ error: "Chat session not found" });
    const guard = assertChatOwnership(session, req);
    if (guard !== true) return res.status(guard.status).json({ error: guard.error });
    // Strip transient streaming flags before persisting.
    const cleanMessages = parsed.data.messages.map(m => ({
      role: m.role,
      content: m.content,
      ...(m.userPrompt ? { userPrompt: m.userPrompt } : {}),
      ...(m.envelope ? { envelope: m.envelope } : {}),
    }));
    const body = JSON.stringify({ messages: cleanMessages });
    if (Buffer.byteLength(body, "utf8") > MAX_CHAT_BYTES) {
      return res.status(413).json({ error: `Chat exceeds ${MAX_CHAT_BYTES} bytes. Start a new chat.` });
    }
    await getObjectStore().putObject({
      key: session.storageKey,
      body,
      contentType: "application/json",
    });
    const title = parsed.data.title?.trim() || (session.title === "New chat" ? deriveTitle(cleanMessages) : session.title);
    const updated = await getStorage().updateChatSession(req.params.id, {
      title,
      messageCount: cleanMessages.length,
      lastMessagePreview: derivePreview(cleanMessages),
    });
    res.json(updated);
  }));

  app.delete("/api/chat-sessions/:id", requireDb, requireActor, asyncHandler(async (req, res) => {
    const session = await getStorage().getChatSession(req.params.id);
    if (!session) return res.status(404).json({ error: "Chat session not found" });
    const guard = assertChatOwnership(session, req);
    if (guard !== true) return res.status(guard.status).json({ error: guard.error });
    try { await getObjectStore().deleteObject(session.storageKey); } catch (e) {
      console.warn("[chat-sessions] delete OBS object failed:", e instanceof Error ? e.message : e);
    }
    await getStorage().deleteChatSession(req.params.id);
    res.status(204).end();
  }));

  // ==========================================================================
  // Report artifacts — server-rendered PDF/XML uploaded to OBS
  // ==========================================================================
  app.get("/api/regulatory-reports/:id/artifacts", requireDb, asyncHandler(async (req, res) => {
    const r = await getStorage().getRegulatoryReport(req.params.id);
    if (!r) return res.status(404).json({ error: "Report not found" });
    res.json(await getStorage().listReportArtifacts(req.params.id));
  }));

  const ArtifactKindSchema = z.object({ kind: z.enum(["PDF", "XML"]) });
  app.post("/api/regulatory-reports/:id/artifacts", requireDb, requireActor, requirePermission("file_reports"), asyncHandler(async (req, res) => {
    const parsed = ArtifactKindSchema.safeParse(req.body ?? {});
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid payload" });
    const storage = getStorage();
    const report = await storage.getRegulatoryReport(req.params.id);
    if (!report) return res.status(404).json({ error: "Report not found" });
    const actor = actorFromReq(req);
    const kind = parsed.data.kind;
    const version = await storage.nextArtifactVersion(report.id, kind);
    const ext = kind === "PDF" ? "pdf" : "xml";
    const mime = kind === "PDF" ? "application/pdf" : "application/xml";
    const fileName = `${report.id}-v${version}.${ext}`;
    const body: Buffer = kind === "PDF"
      ? await renderReportPdf(report)
      : Buffer.from(renderReportXml(report), "utf8");
    const store = getObjectStore();
    const key = generateStorageKey("reports", fileName);
    await store.putObject({ key, body, contentType: mime });
    const id = `RA-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const created = await storage.createReportArtifact({
      id,
      reportId: report.id,
      kind,
      version,
      storageKey: key,
      storageBackend: store.backend,
      sizeBytes: body.length,
      mime,
      createdBy: actor.actorName,
    });
    const url = await store.getSignedDownloadUrl(key, { expiresInSeconds: 600 });
    res.status(201).json({ ...created, downloadUrl: url, expiresInSeconds: 600 });
  }));

  app.get("/api/report-artifacts/:id/download", requireDb, requireActor, asyncHandler(async (req, res) => {
    const artifact = await getStorage().getReportArtifact(req.params.id);
    if (!artifact) return res.status(404).json({ error: "Artifact not found" });
    const url = await getObjectStore().getSignedDownloadUrl(artifact.storageKey, { expiresInSeconds: 600 });
    res.json({ url, key: artifact.storageKey, mime: artifact.mime, expiresInSeconds: 600 });
  }));

  // ==========================================================================
  // Models (Task #40) — registry, evaluation snapshots, lifecycle actions
  // ==========================================================================

  // Models lifecycle RBAC is now centralized through `requirePermission(...)` —
  // see route declarations below. The legacy `checkModelRole(req, [...])`
  // helper has been removed in favour of the shared permission map so that
  // role/permission edits in `generateRoleDefinitions()` flow through
  // unchanged.

  // Adapter: shape the DB row into the front-end's EnhancedMLModel contract.
  // Date columns are serialized to ISO strings so the React types match.
  function toModelDto(m: ModelRow, auditLog: Array<{ id: string; action: string; actor: string; timestamp: string; details: string }> = []) {
    return {
      ...m,
      trainedAt: m.trainedAt instanceof Date ? m.trainedAt.toISOString() : m.trainedAt,
      lastDeployed: m.lastDeployed instanceof Date ? m.lastDeployed.toISOString() : m.lastDeployed,
      createdAt: m.createdAt instanceof Date ? m.createdAt.toISOString() : m.createdAt,
      updatedAt: m.updatedAt instanceof Date ? m.updatedAt.toISOString() : m.updatedAt,
      auditLog,
    };
  }

  function toEvalDto(e: ModelEvaluationRow) {
    return {
      ...e,
      generatedAt: e.generatedAt instanceof Date ? e.generatedAt.toISOString() : e.generatedAt,
    };
  }

  async function loadModelAudit(id: string) {
    const { rows } = await getStorage().listAuditLog({ targetType: "model", targetId: id, limit: 100 });
    return rows.map((r) => ({
      id: r.id,
      action: r.action,
      actor: r.actorName,
      timestamp: (r.createdAt instanceof Date ? r.createdAt : new Date(r.createdAt as unknown as string)).toISOString(),
      details: typeof (r.metadata as { details?: unknown } | null)?.details === "string"
        ? (r.metadata as { details: string }).details
        : JSON.stringify(r.metadata ?? {}),
    }));
  }

  app.get("/api/models", requireDb, asyncHandler(async (_req, res) => {
    const rows = await getStorage().listModels();
    res.json(rows.map((m) => toModelDto(m)));
  }));

  // NOTE: must be registered BEFORE /api/models/:id so it isn't shadowed.
  app.get("/api/models/dashboard", requireDb, asyncHandler(async (_req, res) => {
    const all = await getStorage().listModels();
    const productionModel = all.find((m) => m.stage === "production" && m.category === "supervised")
      ?? all.find((m) => m.stage === "production")
      ?? all[0];
    if (!productionModel) return res.status(404).json({ error: "No models registered." });
    const evaluation = await getStorage().getLatestEvaluation(productionModel.id);
    if (!evaluation) return res.status(404).json({ error: "No evaluation snapshot for production model." });
    const audit = await loadModelAudit(productionModel.id);
    res.json({ productionModel: toModelDto(productionModel, audit), evaluation: toEvalDto(evaluation) });
  }));

  app.get("/api/models/:id", requireDb, asyncHandler(async (req, res) => {
    const m = await getStorage().getModel(req.params.id);
    if (!m) return res.status(404).json({ error: "Model not found" });
    const audit = await loadModelAudit(m.id);
    res.json(toModelDto(m, audit));
  }));

  app.get("/api/models/:id/evaluation", requireDb, asyncHandler(async (req, res) => {
    const e = await getStorage().getLatestEvaluation(req.params.id);
    if (!e) return res.status(404).json({ error: "No evaluation snapshot for this model." });
    res.json(toEvalDto(e));
  }));

  const ActionBody = z.object({ reason: z.string().min(1, "Reason is required.").max(2000) });

  // Promote: target stage='production', demote any other production model in
  // the same category to 'archived', append a version entry, and stamp audit.
  app.post("/api/models/:id/promote", requireDb, requireActor, requirePermission("deploy_models"), asyncHandler(async (req, res) => {
    const parsed = ActionBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid body" });
    const storage = getStorage();
    const target = await storage.getModel(req.params.id);
    if (!target) return res.status(404).json({ error: "Model not found" });
    if (target.stage === "production") return res.status(400).json({ error: "Model is already in production." });
    const actor = actorFromReq(req);
    const all = await storage.listModels();
    for (const m of all) {
      if (m.id !== target.id && m.stage === "production" && m.category === target.category) {
        await storage.updateModel(m.id, { stage: "archived", isActive: false });
        await storage.appendAudit({
          actorUserId: actor.actorUserId, actorName: actor.actorName, action: "Demoted to archived",
          targetType: "model", targetId: m.id, ipAddress: actor.ipAddress,
          metadata: { details: `Replaced by ${target.name} (${target.id}). Reason: ${parsed.data.reason}` },
        });
      }
    }
    const newVersions = [...(target.versions ?? []), {
      version: target.version,
      stage: "production" as const,
      trainedAt: (target.trainedAt instanceof Date ? target.trainedAt : new Date(target.trainedAt as unknown as string)).toISOString().slice(0, 10),
      metrics: { precision: target.metrics.precision, recall: target.metrics.recall, f1Score: target.metrics.f1Score, aucRoc: target.metrics.aucRoc },
    }];
    const updated = await storage.updateModel(target.id, { stage: "production", isActive: true, lastDeployed: new Date(), versions: newVersions });
    await storage.appendAudit({
      actorUserId: actor.actorUserId, actorName: actor.actorName, action: "Promoted to production",
      targetType: "model", targetId: target.id, ipAddress: actor.ipAddress,
      metadata: { details: parsed.data.reason },
    });
    const audit = await loadModelAudit(target.id);
    res.json(toModelDto(updated!, audit));
  }));

  // Rollback: demote a production model back to 'staging' (and clear isActive).
  app.post("/api/models/:id/rollback", requireDb, requireActor, requirePermission("deploy_models"), asyncHandler(async (req, res) => {
    const parsed = ActionBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid body" });
    const storage = getStorage();
    const target = await storage.getModel(req.params.id);
    if (!target) return res.status(404).json({ error: "Model not found" });
    if (target.stage !== "production") return res.status(400).json({ error: "Only production models can be rolled back." });
    const actor = actorFromReq(req);
    const updated = await storage.updateModel(target.id, { stage: "staging", isActive: false });
    await storage.appendAudit({
      actorUserId: actor.actorUserId, actorName: actor.actorName, action: "Rolled back from production",
      targetType: "model", targetId: target.id, ipAddress: actor.ipAddress,
      metadata: { details: parsed.data.reason },
    });
    const audit = await loadModelAudit(target.id);
    res.json(toModelDto(updated!, audit));
  }));

  const ThresholdBody = z.object({
    threshold: z.number().min(0).max(1),
    reason: z.string().min(1, "Reason is required.").max(2000),
  });
  app.post("/api/models/:id/threshold", requireDb, requireActor, requirePermission("deploy_models"), asyncHandler(async (req, res) => {
    const parsed = ThresholdBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid body" });
    const storage = getStorage();
    const target = await storage.getModel(req.params.id);
    if (!target) return res.status(404).json({ error: "Model not found" });
    const actor = actorFromReq(req);
    const updated = await storage.updateModel(target.id, { threshold: parsed.data.threshold });
    await storage.appendAudit({
      actorUserId: actor.actorUserId, actorName: actor.actorName, action: "Threshold adjusted",
      targetType: "model", targetId: target.id, ipAddress: actor.ipAddress,
      metadata: { details: `Threshold changed from ${target.threshold} to ${parsed.data.threshold}. ${parsed.data.reason}` },
    });
    const audit = await loadModelAudit(target.id);
    res.json(toModelDto(updated!, audit));
  }));

  // Retrain: registers a brand new candidate model row (the long-running
  // training job is out of scope; we synthesize a result with a small bump
  // in metrics and copy the source model's evaluation snapshot).
  const RetrainBody = z.object({
    sourceModelId: z.string().optional(),
    modelFamily: z.string().min(1, "Model family required."),
    trainingWindow: z.string(),
    labelSource: z.string(),
    featureSetVersion: z.string(),
    validationStrategy: z.string(),
    kFolds: z.string().optional(),
    minPrecision: z.string(),
    maxFPR: z.string(),
    maxLatencyP95: z.string(),
    reason: z.string().min(1, "Reason is required.").max(2000),
  });
  app.post("/api/models/retrain", requireDb, requireActor, requirePermission("retrain_models"), asyncHandler(async (req, res) => {
    const parsed = RetrainBody.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0]?.message || "Invalid body" });
    const cfg = parsed.data;
    const storage = getStorage();
    const all = await storage.listModels();
    const source = (cfg.sourceModelId && await storage.getModel(cfg.sourceModelId))
      || all.find((m) => m.type === cfg.modelFamily)
      || all.find((m) => m.stage === "production")
      || all[0];
    if (!source) return res.status(400).json({ error: "No source model available to base candidate on." });

    const newId = await storage.nextModelId();
    const bump = (v: number, delta: number) => Math.min(0.999, Math.max(0, +(v + delta).toFixed(4)));
    const newVersionLabel = (() => {
      const m = /v(\d+)\.(\d+)\.?(\d+)?/.exec(source.version);
      if (!m) return `${source.version}-rc1`;
      return `v${m[1]}.${Number(m[2] ?? "0") + 1}.0-rc1`;
    })();
    const candidate: InsertModel = {
      id: newId,
      name: `${source.name} (Retrained ${new Date().toISOString().slice(0, 10)})`,
      type: cfg.modelFamily,
      version: newVersionLabel,
      stage: "candidate",
      healthStatus: "healthy",
      purpose: source.purpose,
      category: source.category,
      owner: actorFromReq(req).actorName,
      description: `Retrained candidate generated from ${source.id} (${source.version}). Reason: ${cfg.reason}`,
      objective: source.objective,
      dataWindow: cfg.trainingWindow,
      trainedAt: new Date(),
      lastDeployed: null,
      trainingDataSize: source.trainingDataSize,
      featuresUsed: source.featuresUsed,
      featureGroups: source.featureGroups,
      primarySegments: source.primarySegments,
      labelRate: source.labelRate,
      limitations: source.limitations,
      knownFailureModes: ["Under evaluation - failure modes not yet characterized"],
      threshold: Number(cfg.minPrecision) > 0 ? source.threshold : source.threshold,
      riskBandMapping: source.riskBandMapping,
      metrics: {
        accuracy: bump(source.metrics.accuracy, 0.01),
        precision: bump(source.metrics.precision, 0.02),
        recall: bump(source.metrics.recall, 0.01),
        f1Score: bump(source.metrics.f1Score, 0.015),
        aucRoc: bump(source.metrics.aucRoc, 0.02),
        falsePositiveRate: Math.max(0, +(source.metrics.falsePositiveRate - 0.005).toFixed(4)),
        truePositiveRate: bump(source.metrics.truePositiveRate, 0.01),
      },
      latencyP50: source.latencyP50,
      latencyP95: source.latencyP95,
      errorRate: source.errorRate,
      uptime: source.uptime,
      throughput: source.throughput,
      driftScore: 0.02,
      alertYield: source.alertYield,
      inferenceVolume: 0,
      alertsGenerated: 0,
      escalationRate: 0,
      confirmedFraudRate: 0,
      isActive: false,
      approvalChain: [{ role: "ML Engineer", name: actorFromReq(req).actorName, action: "Trained & registered as candidate", date: new Date().toISOString().slice(0, 10) }],
      versions: [{ version: newVersionLabel, stage: "candidate", trainedAt: new Date().toISOString().slice(0, 10), metrics: { precision: bump(source.metrics.precision, 0.02), recall: bump(source.metrics.recall, 0.01), f1Score: bump(source.metrics.f1Score, 0.015), aucRoc: bump(source.metrics.aucRoc, 0.02) } }],
    };
    const created = await storage.createModel(candidate);

    const sourceEval = await storage.getLatestEvaluation(source.id);
    if (sourceEval) {
      const evalRow: InsertModelEvaluation = {
        id: `MEVAL-${created.id}-${Date.now().toString(36)}`,
        modelId: created.id,
        featureDrift: sourceEval.featureDrift,
        dataQuality: sourceEval.dataQuality,
        confusionMatrix: sourceEval.confusionMatrix,
        detectionTrend: sourceEval.detectionTrend,
        lossTrend: sourceEval.lossTrend,
        scoreDistribution: sourceEval.scoreDistribution,
        precisionRecallCurve: sourceEval.precisionRecallCurve,
        featureImportance: sourceEval.featureImportance,
        segmentMetrics: sourceEval.segmentMetrics,
        stabilityTrend: sourceEval.stabilityTrend,
        inferenceByChannel: sourceEval.inferenceByChannel,
        whatChanged: [`Retrained candidate ${newVersionLabel} registered. Source: ${source.id} (${source.version}).`, ...sourceEval.whatChanged],
      };
      await storage.upsertEvaluation(evalRow);
    }
    const actor = actorFromReq(req);
    await storage.appendAudit({
      actorUserId: actor.actorUserId, actorName: actor.actorName, action: "Retrain submitted",
      targetType: "model", targetId: created.id, ipAddress: actor.ipAddress,
      metadata: { details: `Source ${source.id}; family ${cfg.modelFamily}; window ${cfg.trainingWindow}. ${cfg.reason}` },
    });
    res.status(201).json(toModelDto(created, await loadModelAudit(created.id)));
  }));
}
